language: julia

os:
  - linux

julia:
  - 1.0

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("EcologicalNetworksPlots")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
